def foo( # 구문 오류